### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [mourinhan8/Ls#1]
1. Аргументы следует разбирать из массива `args` (то есть передаваемые программе извне), а не из входного потока.
2. Используйте `StringBuilder` вместо множественной конкатенации.
3. Список `files` лучше сделать приватным. Если вы хотите проверить в тестах функциональность на искусственном списке файлов, то лучше добавить package-private конструктор от списка файлов (ваши классы, кстати, следует поместить в пакет)
4. В тестах следует проверить вывод во всех форматах. 
5. `listFiles` не даёт вам гарантий порядка вывода файлов, нужно сортировать список самостоятельно.

**Comment by gagarski** [comment]
№4 всё ещё актуально.

1. https://github.com/mourinhan8/Ls/blob/84d81ede285762ca9b7ad2ccda800b7dc0430398/src/Ls.java#L78
Зачем здесь выбрасываете исключение?
2. https://github.com/mourinhan8/Ls/blob/84d81ede285762ca9b7ad2ccda800b7dc0430398/src/Ls.java#L96
Проверять имя файла на корректность регексом не нужно. ПРосто уберите эту проверку.
3. Вывод в файл и на консоль у вас происходит в разном формате.
4. Кроме того, вы выводите на консоль и в файл совершенно разным кодом. Такого быть не должно. Метод `output`, должен принимать выходной поток, в который он будет производить вывод, независимо от того, производится вывод в файл или на консоль. Код для консоли и файла должен отличаться только в месте создания этого потока. 
5. В методе `output` нет большой необходимости создавать одну огромную строку и выводить её в файл. Можно это делать построчно. 
6. https://github.com/mourinhan8/Ls/blob/84d81ede285762ca9b7ad2ccda800b7dc0430398/src/Ls.java#L75
Есть ощущение, что вместо кучи конкатенаций можно это выразить через один `String.format`.

**Comment by gagarski** [comment]
4 и 6 всё ещё актуальны.

По поводу 4: напишите метод, который выводит результат в любой `OutputStream` (передаваемый в аргументе). Затем вызовите этот код для `FileOutputStream` или `OutputStream`, созданный от `System.out`, в зависимости от опций.

**Comment by mourinhan8** [comment]
Скажите мне, пожалуйста, у этой задачи все в порядке. А мне можно сдать экзамне досрочно в 28-ого мая?
